targets:
  $default:
    sources:
      - lib/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/"
          output_folder: "lib/swagger_generated_code/"
          input_urls:
            - url: "http://localhost:3000/api-json"
            